### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: unexpected 'end of print statement' if playbook variable contains '+' sign at the end

### ISSUE THREAD

**Issue by wenditer** [arno49/shaper#12]
`shaper play` fails with error if playbook variable contains '+' sign at the end

Error: 
jinja2.exceptions.TemplateSyntaxError: unexpected 'end of print statement' 

Playbook example:
```
variables:
  env: envName
  apps:
    aux:
    - name: PESaux
      atg:
        Initial:
          initialservices+: 'value'
```

**Comment by arno49** [comment]
Fixed

https://github.com/arno49/shaper/blob/master/tests/assets/expected_out.yml#L30
